/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DuasRouteImport } from './routes/duas'
import { Route as HadithRouteImport } from './routes/hadith'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DuasRoute = DuasRouteImport.update({
  id: '/duas',
  path: '/duas',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithRoute = HadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/duas': typeof DuasRoute
  '/hadith': typeof HadithRoute
  '/quran': typeof QuranRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/duas': typeof DuasRoute
  '/hadith': typeof HadithRoute
  '/quran': typeof QuranRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/duas': typeof DuasRoute
  '/hadith': typeof HadithRoute
  '/quran': typeof QuranRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/ask' | '/auth' | '/duas' | '/hadith' | '/quran' | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ask' | '/auth' | '/duas' | '/hadith' | '/quran' | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/auth'
    | '/duas'
    | '/hadith'
    | '/quran'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  AuthRoute: typeof AuthRoute
  DuasRoute: typeof DuasRoute
  HadithRoute: typeof HadithRoute
  QuranRoute: typeof QuranRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duas': {
      id: '/duas'
      path: '/duas'
      fullPath: '/duas'
      preLoaderRoute: typeof DuasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith': {
      id: '/hadith'
      path: '/hadith'
      fullPath: '/hadith'
      preLoaderRoute: typeof HadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  AuthRoute: AuthRoute,
  DuasRoute: DuasRoute,
  HadithRoute: HadithRoute,
  QuranRoute: QuranRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
